### ISSUE TITLE
Notifying component

### ISSUE THREAD

**Issue by danielacraciun** [danielacraciun/scrape-rec#25]
Should not mess with application structure, optional add-on for personal usage.
Scrapy has [built-in mail](https://docs.scrapy.org/en/0.10.3/topics/email.html). Should we make use of monitors?

**Comment by danielacraciun** [comment]
@mirceachira how should this be done?

**Comment by mirceachira** [comment]
I suggest we create a pipeline for items that checks certain criteria and sends an email when we find something interesting.

This can be done using scrapy's [email](https://docs.scrapy.org/en/latest/topics/email.html) built-in service. This is based on [smtplib](https://docs.python.org/3/library/smtplib.html) 

I guess the first question is how can we classify an apartment as interesting? Can we set a standard or do we want to check the database and see how it compares to the others? Could it be possible to implement a scoring system?

**Comment by danielacraciun** [comment]
#32 might tie in to this.
For now, I suggest an e-mail synchronized with the scraping jobs, which retrieves a JSON with values for certain fields (or ranges & group of values, where it makes sense). Example:
```
{
'price' : {'type': 'range', 'value': [200, 450]},
'surface': {'type': 'range', 'value': [50, 100]},
'neighborhood': ['buna ziua', 'borhanci', 'grigorescu'],
'floor': {'type': 'multiple', 'value': [2, 3, 4]},
'number_of_rooms': {'type': 'single', 'value': 2},
'parking': true,
...
}
```

**Comment by danielacraciun** [comment]
Building on the idea of a scoring system, we could add priority to each field and build a score on that :slightly_smiling_face:

**Comment by danielacraciun** [comment]
TELEGRAM BOT!
